// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcISNccQq2o4gOLdfvVAQBZJ21ptlraos',
    appId: '1:745027684498:web:777bff5bc1f10c4d6e3e4b',
    messagingSenderId: '745027684498',
    projectId: 'arwen-productivity',
    authDomain: 'arwen-productivity.firebaseapp.com',
    storageBucket: 'arwen-productivity.firebasestorage.app',
    measurementId: 'G-SQLHWK53HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgQpRFio9NVC-eArhYYezqxkw2EQGbSN4',
    appId: '1:745027684498:android:8689423deac2d4bb6e3e4b',
    messagingSenderId: '745027684498',
    projectId: 'arwen-productivity',
    storageBucket: 'arwen-productivity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-RR8vucXyqvfEUi5cXS3z7ZJl7O5TxCg',
    appId: '1:745027684498:ios:e42096d12adc33356e3e4b',
    messagingSenderId: '745027684498',
    projectId: 'arwen-productivity',
    storageBucket: 'arwen-productivity.firebasestorage.app',
    androidClientId: '745027684498-565euqlkaibvamoh95n5eugkk5jdjq27.apps.googleusercontent.com',
    iosClientId: '745027684498-mepicleg7ahaolel15n6j8r0k33k9a3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.solitude',
  );

}